signup:
  image: ryan-lane/signup
  #build: .
  #volumes:
  #  - .:/srv/signup:rw
  ports:
   - "80:80"
  links:
   - dynamo
  env_file: ./service.env
  environment:
    HOST: '0.0.0.0'
    PORT: 80
    DYNAMODB_CREATE_TABLE: 'true'
dynamo:
  volumes:
    - /mnt/dynamo:/mnt/dynamo:rw,Z
  ports:
    - "7777:7777"
  image: tray/dynamodb-local
  command: -port 7777 -dbPath /mnt/dynamo
